### ISSUE TITLE
Add rbac support to Protocol and Token

### ISSUE THREAD

**Issue by codingchili** [codingchili/chili-core#110]
Increase granularity of service accessibility from public/authorized to roles.

**Comment by codingchili** [comment]
Associated with #107

**Comment by codingchili** [comment]
Implement as vertx auth provider.

**Comment by codingchili** [comment]
Added properties to tokens, vertx auth provider in another issue.

**Comment by codingchili** [comment]
Add integration with the Protocol for specifying access levels

**Comment by codingchili** [comment]
Added to protocol, custom roles, annotations supported, access levels. To be used with a RoleManager to get the roles from incoming requests. RoleManager TBD

**Comment by veotax** [comment]
[jCasbin](https://github.com/casbin/jcasbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.
4. multiple models like ACL, BLP, RBAC, ABAC, RESTful are supported.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I saw there's a RBAC need here, and I think jCasbin is a good choice. What do you think? Thanks.
